FROM golang:1.23-alpine AS builder

LABEL org.opencontainers.image.source=https://github.com/shrimpsizemoose/kanelbulle

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o /server ./cmd/server

FROM alpine:3.19
COPY --from=builder /server /server
ENTRYPOINT ["/server"]
